image: node:alpine

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install
    # - npm i -g firebase-tools
    # - npm run build
    # - firebase deploy --project joboxza --token "1//03QZb8WbPE2iSCgYIARAAGAMSNwF-L9IrVxdQXGiC-vIe_jNtaMSog1xWaTheTZlj6d-WsncXHQE_z6gXK-1jlZvwdEfqcZWRPTU"

